### ISSUE TITLE
Python sys.exit --> raise

### ISSUE THREAD

**Issue by j08lue** [JesJehle/earthEngineGrabR#2]
Just stubled upon this. What a system - R calling Python to interface GEE and load the data right from there into R's memory. Cool you got this to work!

Just a random note on your Python code -- don't `print` and then `sys.exit` like in

https://github.com/JesJehle/earthEngineGrabR/blob/ae6b6e91473a3e55550f0caf1a75cf946e9087d8/inst/Python/ee_get_data.py#L19-L20

Just `raise ValueError(reducer)` instead, or whatever exception is appropriate. And, btw, Python 2 is dead, so no more `print "..."`. 😉

**Comment by JesJehle** [comment]
Thanks for the hint!
The Python code is still pretty chaotic, I know. 
The revision is planned!

**Comment by mgmanalili** [comment]
Hello, I have successfully installed earthengineGrabR but I was not able to run in properly.

I tried this snippet from the documentation. But I am getting this error even though the file exist in my local machine.

Error: No targetArea specified. 
Please specify a targetArea with a path to a local geo-file of class character.

Thanks!

```{r}
srtm_data <- ee_grab(data = ee_data_image(datasetID = "CGIAR/SRTM90_V4",
                                          spatialReducer = "mean",
                                          scale = 100,
                                          bandSelection = "elevation"
),
targetArea = system.file("data/territories.shp", package = "earthEngineGrabR")
)
