### ISSUE TITLE
Error: Module gdal could not be imported

### ISSUE THREAD

**Issue by bwcastillo** [JesJehle/earthEngineGrabR#9]
Hi, I have a problem when i execute "ee_grab_install" function. The functions work until the following error:

"Error: Installation problem
 Error: Module gdal could not be imported"

I'was guessing that could be because i didn't install gdal from Anaconda I tried with:

"conda install -c conda-forge gdal"

But really I don't know that could be. If u can help me I will be very gratefully a lot.

Regards!

**Comment by JesJehle** [comment]
Since I removed sf as a dependency, this issue should be solved.
